language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - php /home/travis/.phpenv/versions/5.3.26/bin/composer.phar self-update

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit